CREATE TABLE IF NOT EXISTS redirects(
    id VARCHAR(32) NOT NULL,
    url TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS redirect_keys(
    id INT AUTO_INCREMENT,
    content TEXT NOT NULL,
    PRIMARY KEY (id)
);
